Reduce use of redundant word "Rust"
rust-unofficial/awesome-rust pull request #1663
Opened 2024-02-18 03:05 UTC by jayvdb

2024-02-18 21:48 UTC, palfrey requested changes
Thanks for this, I think that's definitely an improvement. Got a few small items that need fixing though.

2024-02-18 21:48 UTC, palfrey commented on README.md
> +* [Thinkofname/rust-quake](https://github.com/Thinkofname/rust-quake) — Quake map renderer,
`,` should be a `.` (or removed)

2024-02-18 23:02 UTC, jayvdb commented
Updated @palfrey. Thanks for catching those.

2024-02-19 00:01 UTC, palfrey approved these changes

2024-02-19 00:06 UTC, merged